---
title: "Missing data processing"
author: "Puvvula"
date: "10/6/2021"
output: pdf_document
---

```{r}
#load libraries
library(tidyverse)
library(janitor)
library(skimr)
library(lubridate)
library(gridExtra)
library(lemon)
```


```{r}
#load clean data 
dat<- as_tibble(read_csv("/work/jessebell/puvvula/aqd_final_data/merged_fin.csv"))

skimr::skim(dat)
clean_names(dat)

#Add row identifier
dat$ID<- seq.int(nrow(dat))

### Extract/Formatting date variables
#Added 4 variables extracted from date

dat$date <- as.Date(dat$date, format = "%m/%d/%Y")
dat$month<- as.factor(month(dat$date))
dat$year<- as.factor(format(dat$date, '%Y'))
dat$dow <- wday(as.Date(dat$date, format = "%m/%d/%Y"))
weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
dat$wDay <- factor((weekdays(dat$date) %in% weekdays1), 
                       levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))

seasons = function(x){
  if(x %in% 2:4) return("Spring")
  if(x %in% 5:7) return("Summer")
  if(x %in% 8:10) return("Fall")
  if(x %in% c(11,12,1)) return("Winter")
}

dat$Season = as.factor(sapply(month(dat$date), seasons))
```


```{r}
#visualize missing data

missing.values <- dat %>%
  gather(key = "key", value = "val") %>%
  mutate(isna = is.na(val)) %>%
  group_by(key) %>%
  mutate(total = n()) %>%
  group_by(key, total, isna) %>%
  summarise(num.isna = n()) %>%
  mutate(pct = num.isna / total * 100)
levels <- (missing.values  %>% filter(isna == T) %>%     
           arrange(desc(pct)))$key
percentage.plot <- missing.values %>%
      ggplot() +
        geom_bar(aes(x = reorder(key, desc(pct)), 
                     y = pct, fill=isna), 
                  stat = 'identity', alpha=0.8) +
        scale_x_discrete(limits = levels) +
        scale_fill_manual(name = "", 
                          values = c('steelblue', 'tomato3'), 
                          labels = c("Present", "Missing")) +
        coord_flip() +
        labs(title = "Percentage of missing values", 
             x = 'Variable', y = "% of missing values")
percentage.plot

#######################################
#### ROW PLOT ###################
# provides detailed view
row.plot <- dat %>%
  mutate(id = row_number()) %>%
  gather(-id, key = "key", value = "val") %>%
  mutate(isna = is.na(val)) %>%
  ggplot(aes(key, id, fill = isna)) +
    geom_raster(alpha=0.8) +
    scale_fill_manual(name = "",
        values = c('steelblue', 'tomato3'),
        labels = c("Present", "Missing")) +
    scale_x_discrete(limits = levels) +
    labs(x = "Variable",
           y = "Row Number", title = "Missing values in rows") +
    coord_flip()
row.plot


grid_arrange_shared_legend(percentage.plot,row.plot)
```

Imputing missing values

```{r}
# Data imputation - TBD
library(pcaMethods)

pc <- pca(dat, method="ppca")
pca_imputed <- completeObs(pc)

write.csv(pca_imputed, "/work/jessebell/puvvula/aqd_raw/pca_imputed.csv", 
          row.names = T)

```

```{r}

#select date and append date to imputed dataset
date_join<- dat %>% select(row_id, date)
imp_dat<- read_csv("/work/jessebell/puvvula/aqd_raw/pca_imputed.csv")

#imputed data with date variable
merged_data<- left_join(imp_dat,date_join, by="row_id")

write.csv(merged_data, "/work/jessebell/puvvula/aqd_raw/final_imputed.csv", 
          row.names = F)

```


```{r}
#working with imputed dataset

dat<- read_csv("/work/jessebell/puvvula/aqd_raw/final_imputed.csv")





```

