---
title: "08_mixture_analysis"
author: "Puvvula"
date: "11/12/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(lubridate)
library(zoo)
library(gWQS)


dat<- read_csv("/work/jessebell/puvvula/aqd_final_data/pAsthma_imputed.csv")

dat$date<- as.Date(dat$date, format = "%m/%d/%Y")
yq <- as.yearqtr(as.yearmon(dat$date, "%Y %m/%d/") + 1/12)
dat$season <- factor(format(yq, "%q"), levels = 1:4,
                     labels = c("winter", "spring", "summer", "fall"))

dat.winter<- dat %>% subset(season =="winter")
dat.spring<- dat %>% subset(season =="spring")
dat.summer<- dat %>% subset(season =="summer")
dat.fall<- dat %>% subset(season =="fall")

```

#mixture model
#Mixture of 52 air pollutants
# 08 - Criteria pollutants
# 17 - Tree pollen
# 08 - Weed pollen
# 01 - Grass pollen
# 01 - Unknown pollen
# 17 - Mold
# covariates: daily temperature, wind speed, wind direction
```{r}
mixture<- names(dat.summer[8:59])

#gWQS
m1 = gwqs(p_ast ~ wqs+TMAX+WDF2+WSF2,
          mix_name = mixture, data = dat.summer, q = 10,
          validation = 0.8, b = 100, b1_pos = TRUE, b1_constr = TRUE,
          family = "negbin",
          seed = 2021)
```
#Model summary: for regular model
gwqs_summary_tab(m1)
gwqs_scatterplot(m1)
gwqs_barplot(m1)
summary(m1$fit)
m1$final_weights

```{r}
#gWQS with repeated holdout
#Suggested repeated holdout >30
mixture<- names(dat.summer[8:59])
m1_rh = gwqsrh(p_ast ~ wqs+TMAX+WDF2+WSF2,
          mix_name = mixture, data = dat, q = 10,
          validation = 0.8, b = 100, b1_pos = TRUE, b1_constr = TRUE,
          family = "negbin",
          seed = 2021, rh=10)

#Model summary: For repeated holdout
gwqs_summary_tab(m1_rh)
gwqsrh_boxplot(m1_rh)
gwqs_weights_tab(m1_rh)
summary(m1_rh$fit)
```

#sankey diagram - Change in pollutant weight by lag 
```{r}
library(tidyverse)
library(ggalluvial)

data("majors")

pol_wt<- read_csv("/work/jessebell/puvvula/aqd_final_data/pollu_weight.csv")

majors$curriculum <- as.factor(majors$curriculum)

#semester to lag0-lag5
#stratum to pollutant
#alluvium to weight

pol_wt$lag<- as.factor(pol_wt$lag)
pol_wt$pollutant<- as.factor(pol_wt$pollutant)

ggplot(pol_wt, aes(x = lag, stratum = pollutant,alluvium = lag),
       fill = weight,label = pollutant)


+
  scale_fill_brewer(type = "qual", palette = "Set2") +
  geom_flow(stat = "alluvium", lode.guidance = "frontback",
            color = "darkgray") +
  geom_stratum() +
  theme(legend.position = "bottom") +
  ggtitle("student curricula across several semesters")


```

