---
title: "10_SDoH"
author: "Puvvula"
date: "12/21/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(corrplot)

dat<- read_csv("/work/jessebell/puvvula/Ne-sdoh_jan.csv")

dat_n <- dat[c(2,3,7:23)]

M<-cor(dat_n)

cor.mtest <- function(mat, ...) {
  mat <- as.matrix(mat)
  n <- ncol(mat)
  p.mat<- matrix(NA, n, n)
  diag(p.mat) <- 0
  for (i in 1:(n - 1)) {
    for (j in (i + 1):n) {
      tmp <- cor.test(mat[, i], mat[, j], ...)
      p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
    }
  }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
# matrix of the p-value of the correlation
p.mat <- cor.mtest(dat_n)

#Correlation matrix
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(M, method="color", col=col(200),  
         type="upper", order="original", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE)

```


```{r}
#Spatial analysis using CARbayes
#https://www.ravenmcknight.com/post/carbayes-tutorial/

library(tidyverse)
library(sf)
library(spdep)
library(CARBayes)
library(janitor)

dat<- read_sf("env_asth/env_asth_analysis.shp")

#g1= under 5 years
#g2= 5-9 years
#g3= 10-14 years
#g4= 15-19 years
dat<- dat %>% rename(male_ar=Ne_sdoh__1,female_ar=Ne_sdoh__2,
                     E_TOTPOP=Ne_sdoh__3,unins_lt6yr=Ne_sdoh__4,
                     unins_7_18yr=Ne_sdoh__5, owner_occ=Ne_sdoh__6,
                     rente_occu=Ne_sdoh__7, ssi_snap=Ne_sdoh__8,
                     hispanic=Ne_sdoh__9,blk=Ne_sdoh_10,white=Ne_sdoh_11,
                     E_POV=Ne_sdoh_12,unemp=Ne_sdoh_13,pci=Ne_sdoh_14,
                     nohsdp=Ne_sdoh_15,sing_prnt=Ne_sdoh_16,
                     minority=Ne_sdoh_17,limlang=Ne_sdoh_18,crowd=Ne_sdoh_19,
                     noveh=Ne_sdoh_20,zip=Ne_sdoh_21,
                     g1f_cnt=Ne_sdoh_22,g1f_pop=Ne_sdoh_23,
                     g1m_cnt=Ne_sdoh_24,g1m_pop=Ne_sdoh_25,
                     g2f_cnt=Ne_sdoh_26,g2f_pop=Ne_sdoh_27,
                     g2m_cnt=Ne_sdoh_28,g2m_pop=Ne_sdoh_29,
                     g3f_cnt=Ne_sdoh_30,g3f_pop=Ne_sdoh_31,
                     g3m_cnt=Ne_sdoh_32,g3m_pop=Ne_sdoh_33,
                     g4f_cnt=Ne_sdoh_34,g4f_pop=Ne_sdoh_35,
                     g4m_cnt=Ne_sdoh_36,g4m_pop=Ne_sdoh_37)


map_theme <- theme_minimal() + theme(text = element_text(color = "#60717a"), 
                                     panel.grid = element_line("transparent"), 
                                     axis.text = element_blank()) 

map_colors <- scale_fill_gradientn(colors = c("#FFBD71", "#FCA464", "#F87D7B", 
                                              "#D04A73"),na.value = "#e1e5e8")

ggplot(dat) +
  geom_sf(aes(fill = dat$Ne_sdoh__1)) +
  map_theme +
  map_colors +
  labs(title = "Ped_asthma", 
       fill = "rate per 100,000")


col_sp <- as(dat, "Spatial")
col_nb <- poly2nb(col_sp) 
col_listw <- nb2listw(col_nb, style = "B") # listw version of the neighborhood
W <- nb2mat(col_nb, style = "B") # binary structure

#spatial clustering
moran.mc(col_sp$Ne_sdoh__1, listw = col_listw, nsim = 999, 
         alternative = "greater") # moran's I test HOVAL


#spatial model
set.seed(2021)
formula<- g1f_cnt~ ssi_snap
m1 <- CARBayes::S.CARleroux(formula,
                            data = dat,
                            W = W,
                            family = "poisson",
                            burnin = 20000,
                            n.sample = 100000,
                            thin = 10)

model.hoval

#clustering of predictor from above model
moran.mc(x = as.vector(model.hoval$residuals$response), 
         listw = col_listw, 
         nsim = 9999, 
         alternative = "greater")

#plot output from model above

dat %>%
  mutate(resid = model.hoval$residuals$response) %>%
  ggplot(aes(fill = resid)) +
  geom_sf() + 
  map_theme +
  map_colors +
  labs(title = "Residuals from the CAR model", 
       subtitle = "Pediatric asthma ~ predictor", 
       fill = "Residual")




```

